# Aspects of this code have been sourced from: https://github.com/moq/Moq.AutoMocker/blob/master/.github/workflows/dotnetcore.yml
name: Continuous

on:
  pull_request:
  
  push:
    branches: [ main ]
    tags:
    - 'v*'
    paths-ignore:
    - 'README.md'

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3

    - name: .NET Test
      run: dotnet test --configuration Release

    - name: .NET Pack
      run: |
        if ('${{ github.ref }}' -match '^refs/tags/v') {
          $match = [regex]::Match('${{ github.ref }}', '^refs/tags/v([0-9]+(\.[0-9]+){1,2})')
          if ($match.Success) {
            $env:VersionPrefix = $match.Groups[1].Value
          } else {
            throw 'Invalid tag version: ${{ github.ref }}'
          }
        }
        else {
          <# All other pushes get a "alpha" suffix #>
          $env:VersionSuffix = 'alpha-{0:00}' -f ${{ github.run_number }}
        }

        dotnet pack --configuration Release --output .
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: NuGet
        if-no-files-found: error
        path: |
          **/*.nupkg
          **/*.snupkg

    - name: Publish NuGet and GitHub
      if: github.event_name == 'push'
      run: |
        dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate
        dotnet nuget push *.nupkg `
          --source 'https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json' `
          --api-key '${{ secrets.GITHUB_TOKEN }}' `
          --skip-duplicate