# Aspects of this code have been sourced from: https://github.com/moq/Moq.AutoMocker/blob/master/.github/workflows/dotnetcore.yml
name: Continuous Build Workflow

on:
  pull_request:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3

    - name: Install Required .NET Tools
      run: |
        dotnet new tool-manifest
        dotnet tool install dotnet-reportgenerator-globaltool
        dotnet tool install dotnet-coverage

    - name: .NET Build
      run: dotnet build --configuration "Release"

    - name: .NET Test and Collect Coverage
      run: dotnet test --configuration "Release" --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Generate Report
      run: |
        dotnet reportgenerator -reports:"**/coverage/**/coverage.cobertura.xml" -targetdir:"./coverage/coveragereport" -reporttypes:"MarkdownSummaryGithub;Html"

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: coveragereport
        path: ./coverage/coveragereport

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        header: 'Coverage-Report"'
        message: |
          Package Coverage Report
        path: ./coverage/coveragereport/SummaryGithub.md
