# Aspects of this code have been sourced from: https://github.com/moq/Moq.AutoMocker/blob/master/.github/workflows/dotnetcore.yml
name: Continuous Build Workflow

on:
  pull_request:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3

    - name: Install .NET Manifest Tool
      run: dotnet new tool-manifest

    - name: Install .NET Report Generator Tool
      run: dotnet tool install dotnet-reportgenerator-globaltool

    - name: Install .NET Coverage Tool
      run: dotnet tool install dotnet-coverage

    - name: .NET Build
      run: dotnet build --configuration "Release"

    - name: .NET Test
      run: dotnet test --configuration "Release" --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Generate Report
      run: |
        dotnet reportgenerator -reports:"**/coverage/**/coverage.cobertura.xml" -targetdir:"./coverage/coveragereport" -reporttypes:MarkdownSummaryGithub